language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
  - public
  - .cache
deploy:
  provider: s3
  bucket: "nempolitik"
  endpoint: s3.eu-central-003.backblazeb2.com
  edge: true
  local_dir: ./public
  on:
    branch: master
before_script:
  - "yarn global add gatsby-cli"
  - "yarn"