language: node_js
node_js:
  - "stable"
cache:
yarn: true
  directories:
  - node_modules
  - public
  - .general
deploy:
  provider: s3
  access_key_id: <encrypted access_key_id>
  secret_access_key: <encrypted secret_access_key>
  bucket: "nempolitik"
  endpoint: s3.eu-central-003.backblazeb2.com
  edge: true
  local_dir: ./public
  on:
    branch: master
before_script:
  - "yarn global add gatsby-cli"
  - "yarn"