backend:
    name: github
    repo: simse/nempolitik

media_folder: "/static/images"
public_folder: "/static/images"


collections:
    - name: "party"
      label: "Party"
      folder: "content/parties"
      create: true
      slug: "{{name}}-{{symbol}}"
      fields:
        - {label: "ID", name: "id", widget: "uuid"}
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Symbol", name: "symbol", widget: "string"}
        - {label: "Headquarters", name: "headquarters", widget: "string"}
        - {label: "Political Leaning", name: "political_leaning", widget: "number"}
        - {label: "Color", name: "color", widget: "string"}
        - {label: "Dark Text", name: "dark_text", widget: "boolean"}
        - {label: "Logo", name: "logo", widget: "image"}
        - {label: "Monochrome Logo", name: "monochrome_logo", widget: "image"}


    - name: "political_entity"
      label: "Political Entity"
      folder: "content/political_entities"
      create: true
      slug: "{{name}}"
      fields:
        - {label: "ID", name: "id", widget: "uuid"}
        - {label: "Type", name: "type", widget: "select", options: ["parliament", "cabinet"]}
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Group Name", name: "group_name", widget: "string", required: false}
        - {label: "Logo", name: "logo", widget: "image"}

    - name: "political_entity_group"
      label: "Political Entity Group"
      folder: "content/political_entity_groups"
      create: true
      slug: "{{name}}"
      fields:
        - {label: "ID", name: "id", widget: "uuid"}
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Political Entities", name: "political_entities", widget: "relation", collection: "political_entity", searchFields: ["name"], valueField: "id", displayFields: ["name"], multiple: false}
        - {label: "Chairman", name: "chairman", widget: "relation", collection: "politician", searchFields: ["name"], valueField: "id", displayFields: ["name"]}
        - {label: "Vice Chairman", name: "vice_chairman", widget: "relation", collection: "politician", searchFields: ["name"], valueField: "id", displayFields: ["name"], required: false}
        - {label: "Members", name: "politicians", widget: "relation", collection: "politician", searchFields: ["name"], valueField: "id", displayFields: ["name"], multiple: true}

    - name: "political_entity_membership_type"
      label: "Political Entity Membership Type"
      folder: "content/political_entity_membership_types"
      create: true
      slug: "{{name}}"
      fields:
        - {label: "ID", name: "id", widget: "uuid"}
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Importance", name: "importance", widget: "number"}
        - {label: "Political Entities", name: "political_entities", widget: "relation", collection: "political_entity", searchFields: ["name"], valueField: "id", displayFields: ["name"], multiple: true}

    - name: "political_entity_membership"
      label: "Political Membership"
      folder: "content/political_entity_memberships"
      create: true
      slug: "{{political_entity}}-{{political_entity_membership_type}}-{{politician}}"
      identifier_field: politician
      fields:
        - {label: "ID", name: "id", widget: "uuid"}
        - {label: "From", name: "from", widget: "date"}
        - {label: "To", name: "to", widget: "date", required: false, default: ""}
        - {label: "Political Entity", name: "political_entity", widget: "relation", collection: "political_entity", searchFields: ["name"], valueField: "id", displayFields: ["name"]}
        - {label: "Political Membership Type", name: "political_entity_membership_type", widget: "relation", collection: "political_entity_membership_type", searchFields: ["name"], valueField: "id", displayFields: ["name"]}
        - {label: "Politician", name: "politician", widget: "relation", collection: "politician", searchFields: ["name"], valueField: "id", displayFields: ["name"]}

    - name: "politician" # Used in routes, e.g., /admin/collections/blog
      label: "Politician" # Used in the UI
      folder: "content/politicians" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{first_name}}-{{last_name}}-{{birthday}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
        - {label: "ID", name: "id", widget: "uuid"}
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Photo", name: "photo", widget: "image"}
        - {label: "Photo Credit", name: "photo_credit", widget: "string"}
        - {label: "Phone number", name: "phone_number", widget: "string", required: false}
        - {label: "Email", name: "email", widget: "string", required: false}
        - {label: "Birthday", name: "birthday", widget: "date", required: false}
        - {label: "Birth Place", name: "birth_place", widget: "string", required: false}
        - {label: "Party Affiliation", name: "party", widget: "relation", collection: "party", searchFields: ["name"], valueField: "id", displayFields: ["name"]}
        - label: "CV"
          name: "experience"
          widget: list
          required: false
          fields:
            - {label: "Place", name: "place", widget: string, required: false}
            - {label: "Title", name: "title", widget: string}
            - {label: "from", name: "from", widget: string}
            - {label: "to", name: "to", widget: string, required: false}
            - {label: "Type", name: "type", widget: "select", options: ["work", "education"]}
        